import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import {Roboto} from "next/font/google";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"]
});


export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {children}
      </body>
    </html>
  );
}
